services:
  - type: web
    name: discord-welcome-bot
    runtime: python3
    environment:
      PYTHON_VERSION: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: discord-bot-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
